import express from "express";
import { InvoiceController } from "./invoice.controller.js";
import validateRequest from "../../middlewares/validateRequest.js";
import { InvoiceValidation } from "./invoice.validation.js";
const router = express.Router();
router.post("/", validateRequest(InvoiceValidation.createInvoiceZodSchema), InvoiceController.createInvoice);
router.get("/", InvoiceController.getAllInvoices);
router.get("/:id", InvoiceController.getInvoiceById);
router.patch("/:id", validateRequest(InvoiceValidation.updateInvoiceZodSchema), InvoiceController.updateInvoice);
router.delete("/:id", InvoiceController.deleteInvoice);
router.post("/generate-monthly", InvoiceController.generateMonthlyInvoices);
router.patch("/:id/mark-paid", InvoiceController.markInvoiceAsPaid);
router.get("/workshop/:workshopId", InvoiceController.getInvoicesByWorkshopId);
export const InvoiceRouter = router;
